### ISSUE TITLE
City map

### ISSUE THREAD

**Issue by Milk-Cool** [il-an/letovo_linkedin_city#12]
- [ ] City map design
- [ ] Buildings on city map
- [ ] Other objects on city map

in progress
