### ISSUE TITLE
Website connection

### ISSUE THREAD

**Issue by Milk-Cool** [il-an/letovo_linkedin_city#9]
- [ ] Enable player authorization via website accounts
- [ ] Make it possible to see user info by clicking a player
- [ ] Saving the players' currency balances

not done yet

**Comment by Milk-Cool** [comment]
it turns out it's a duplicate: #2
